name = "iPEPS"
uuid = "01e728fb-b642-4ffa-9b05-4a090a979482"
authors = ["'yitan1 <yitam98@gmaimail.com>'"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
