# [optim]
# methods = "LBFGS()"
# max_iter = 100

# [ctmrg]
out_prefix = "test"
model = "test"

dir = 0 # 0 -> default dir, string -> dir name

D = 2
chi = 32

resume = false

es_resume = 1 # start from which basis(>0) 
es_num = 0    # calculate how many basis(>0)

# true -> load exist basis, false -> calculate basis
basis = false
basis_t = "default" # "default", "gauge", "cut", "unit"
basis_cut = 1e-3 # when basis_t = "cut", float

ad = true
gc = true
save = true
part_save = false

nrmB_cut = 1e-3 # float or Int

min_iter = 4
max_iter = 20
ad_max_iter = 4
rg_tol = 1e-6

wp = 1  #should wp_name + 1
wp_name = 0 #basis


