# [optim]
# methods = "LBFGS()"
# max_iter = 100

# [ctmrg]
out_prefix = "g11"
model = "hb"

dir = 0 # 0 -> default dir, string -> dir name

D = 2
chi = 32

resume = false

es_resume = 1 # start from which basis(>0) 
es_num = 0    # calculate how many basis(>0)

# true -> load exist basis, false -> calculate basis
basis = false
basis_t = "default" # "default", "gauge", "cut", "unit"

ad = true
gc = true
save = true
part_save = false

basis_cut = 1e-3
nrmB_cut = 57

min_iter = 4
max_iter = 30
ad_max_iter = 4
rg_tol = 1e-6


