# [optim]
# methods = "LBFGS()"
# max_iter = 100

# [ctmrg]
out_prefix = "test"
model = "hb"

D = 2
chi = 64

resume = false

# true -> load exist basis, false -> calculate basis
basis = false

ad = false

nrmB_cut = 1e-3

min_iter = 4
max_iter = 20
ad_max_iter = 4
rg_tol = 1e-6


