# [optim]
# methods = "LBFGS()"
# max_iter = 100

# [ctmrg]
out_prefix = "default"
model = "ising"

D = 2
chi = 30

resume = true

# true -> load exist basis, false -> calculate basis
basis = true

nrmB_cut = 1e-3

min_iter = 4
max_iter = 30
rg_tol = 1e-6


