# [optim]
# methods = "LBFGS()"
# max_iter = 100

# [ctmrg]
out_prefix = "g11"
model = "hb"

D = 4
chi = 64

resume = false

es_resume = 1 # start from which basis(>0) 
es_num = 0    # calculate how many basis(>0)

# true -> load exist basis, false -> calculate basis
basis = false
unit_basis = false

ad = true
gc = true
save = true

nrmB_cut = 20

min_iter = 4
max_iter = 40
ad_max_iter = 20
rg_tol = 1e-3


