# [optim]
# methods = "LBFGS()"
# max_iter = 100

# [ctmrg]
out_prefix = "test"
model = "hb"

D = 2
chi = 64

resume = false

es_resume = 1 # start from which basis(>0) 
es_num = 10    # calculate how many basis(>0)

# true -> load exist basis, false -> calculate basis
basis = false
unit_basis = true

ad = true
gc = true
save = true

nrmB_cut = 1e-3

min_iter = 4
max_iter = 20
ad_max_iter = 4
rg_tol = 1e-6


